imports:
    - { resource: actions.yml }
    - { resource: storage.yml }

parameters:
    # Controllers
    netgen_information_collection.controller.class: Netgen\Bundle\InformationCollectionBundle\Controller\InformationCollectionController
    netgen_information_collection.form.builder.class: Netgen\Bundle\InformationCollectionBundle\Form\Builder\FormBuilder
    # END of Controllers

    # Listeners
    netgen_information_collection.listener.class: Netgen\Bundle\InformationCollectionBundle\Listener\InformationCollectedListener
    # END of Listeners

    # Handler registry
    netgen_information_collection.field_handler.registry.class: Netgen\Bundle\InformationCollectionBundle\FieldHandler\FieldHandlerRegistry
    # END of Handler registry

    # Factories
    netgen_information_collection.factory.email_data.class: Netgen\Bundle\InformationCollectionBundle\Factory\EmailDataFactory
    netgen_information_collection.factory.field_data.class: Netgen\Bundle\InformationCollectionBundle\Factory\FieldDataFactory
    # END of Factories
services:
    netgen_information_collection.controller:
        class: '%netgen_information_collection.controller.class%'
        arguments:
            - '@netgen_information_collection.form.builder'
            - '@event_dispatcher'

    information_collection:
        alias: 'netgen_information_collection.controller'

    netgen_information_collection.form.builder:
        class: '%netgen_information_collection.form.builder.class%'
        arguments:
            - '@form.factory'
            - '@ezpublish.api.service.content_type'
            - '@router'
            - '%netgen.default.information_collection.form.use_csrf%'

    netgen_information_collection.listener:
        class: '%netgen_information_collection.listener.class%'
        arguments:
            - '@netgen_information_collection.action.registry'
        tags:
            - { name: kernel.event_subscriber }

    netgen_information_collection.field_handler.registry:
        class: '%netgen_information_collection.field_handler.registry.class%'

    netgen_information_collection.factory.email_data:
        class: '%netgen_information_collection.factory.email_data.class%'
        arguments:
            - '@ezpublish.config.resolver'
            - '@ezpublish.translation_helper'
            - '@ezpublish.field_helper'
            - '@ezpublish.api.service.content_type'

    netgen_information_collection.factory.field_data:
        class: '%netgen_information_collection.factory.field_data.class%'
        arguments:
            - '@netgen_information_collection.field_handler.registry'
