imports:
    - { resource: actions.yml }

parameters:
    # Controllers
    netgen_information_collection.controller.class: Netgen\Bundle\InformationCollectionBundle\Controller\InformationCollectionController
    netgen_information_collection.form.builder.class: Netgen\Bundle\InformationCollectionBundle\Form\Builder\FormBuilder
    # END of Controllers

    # Doctrine parameteters for information collection
    netgen_information_collection.repository.ez_info_collection.class: Netgen\Bundle\InformationCollectionBundle\Repository\EzInfoCollectionRepository
    netgen_information_collection.entity.ez_info_collection.class: Netgen\Bundle\InformationCollectionBundle\Entity\EzInfoCollection
    netgen_information_collection.repository.ez_info_collection_attribute.class: Netgen\Bundle\InformationCollectionBundle\Repository\EzInfoCollectionAttributeRepository
    netgen_information_collection.entity.ez_info_collection_attribute.class: Netgen\Bundle\InformationCollectionBundle\Entity\EzInfoCollectionAttribute
    # END of Doctrine parameters

    # Listeners
    netgen_information_collection.listener.class: Netgen\Bundle\InformationCollectionBundle\Listener\InformationCollectedListener
    # END of Listeners

    # Handler registry
    netgen_information_collection.field_handler.registry.class: Netgen\Bundle\InformationCollectionBundle\FieldHandler\FieldHandlerRegistry
    # END of Handler registry

    # Factories
    netgen_information_collection.factory.email_data.class: Netgen\Bundle\InformationCollectionBundle\Factory\EmailDataFactory
    netgen_information_collection.factory.field_data.class: Netgen\Bundle\InformationCollectionBundle\Factory\FieldDataFactory
    # END of Factories
services:
    netgen_information_collection.controller:
        class: '%netgen_information_collection.controller.class%'
        arguments:
            - '@netgen_information_collection.form.builder'
            - '@event_dispatcher'

    netgen_information_collection.form.builder:
        class: '%netgen_information_collection.form.builder.class%'
        arguments:
            - '@form.factory'
            - '@ezpublish.api.service.content_type'
            - '@router'
            - '%netgen.default.information_collection.form.use_csrf%'

    # Info collection repositories
    netgen_information_collection.repository.ez_info_collection:
        class: "%netgen_information_collection.repository.ez_info_collection.class%"
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [ "%netgen_information_collection.entity.ez_info_collection.class%" ]

    netgen_information_collection.repository.ez_info_collection_attribute:
        class: "%netgen_information_collection.repository.ez_info_collection_attribute.class%"
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [ "%netgen_information_collection.entity.ez_info_collection_attribute.class%" ]
    # END of Info collection repositories

    netgen_information_collection.listener:
        class: '%netgen_information_collection.listener.class%'
        arguments:
            - '@netgen_information_collection.action.registry'
        tags:
            - { name: kernel.event_subscriber }

    netgen_information_collection.field_handler.registry:
        class: '%netgen_information_collection.field_handler.registry.class%'

    netgen_information_collection.factory.email_data:
        class: '%netgen_information_collection.factory.email_data.class%'
        arguments:
            - '@ezpublish.config.resolver'
            - '@ezpublish.translation_helper'
            - '@ezpublish.field_helper'

    netgen_information_collection.factory.field_data:
        class: '%netgen_information_collection.factory.field_data.class%'
        arguments:
            - '@netgen_information_collection.field_handler.registry'