parameters:
    netgen_information_collection.action.registry.class: Netgen\Bundle\InformationCollectionBundle\Action\ActionRegistry
    netgen_information_collection.action.db.class: Netgen\Bundle\InformationCollectionBundle\Action\DatabaseAction
    netgen_information_collection.action.email.class: Netgen\Bundle\InformationCollectionBundle\Action\EmailAction

services:
    netgen_information_collection.action.registry:
        class: '%netgen_information_collection.action.registry.class%'
        arguments:
            - "$actions;netgen_information_collection$"
            - "@logger"

    netgen_information_collection.action.db:
        class: '%netgen_information_collection.action.db.class%'
        arguments:
            - '@netgen_information_collection.factory.field_data'
            - '@netgen_information_collection.repository.ez_info_collection'
            - '@netgen_information_collection.repository.ez_info_collection_attribute'
            - '@ezpublish.api.repository'
        tags:
            - { name: netgen_information_collection.action, alias: database }

    netgen_information_collection.action.email:
        class: '%netgen_information_collection.action.email.class%'
        arguments:
            - '@netgen_information_collection.factory.email_data'
            - '@netgen_information_collection.mailer'
        tags:
            - { name: netgen_information_collection.action, alias: email }
