services:
    netgen_information_collection.factory.email_data:
        class: Netgen\Bundle\InformationCollectionBundle\Factory\EmailDataFactory
        arguments:
            - "@ezpublish.config.resolver"
            - '@ezpublish.translation_helper'
            - '@ezpublish.field_helper'
            - '@ezpublish.api.service.content'
            - '@twig'

    netgen_information_collection.factory.auto_responder_data:
        class: Netgen\Bundle\InformationCollectionBundle\Factory\AutoResponderDataFactory
        arguments:
            - "@ezpublish.config.resolver"
            - '@ezpublish.translation_helper'
            - '@ezpublish.field_helper'
            - '@ezpublish.api.service.content'
            - '@twig'

    netgen_information_collection.factory.field_data:
        class: Netgen\Bundle\InformationCollectionBundle\Factory\FieldDataFactory
        arguments:
            - '@netgen_information_collection.field_handler.registry'

    netgen_information_collection.factory.captcha:
        class: Netgen\Bundle\InformationCollectionBundle\Form\Captcha\CaptchaService
        arguments:
            - "@ezpublish.api.service.content_type"
            - "@ezpublish.config.resolver"
