parameters:
    netgen_information_collection.factory.email_data.class: Netgen\Bundle\InformationCollectionBundle\Factory\EmailDataFactory
    netgen_information_collection.factory.field_data.class: Netgen\Bundle\InformationCollectionBundle\Factory\FieldDataFactory
    netgen_information_collection.factory.auto_responder_data.class: Netgen\Bundle\InformationCollectionBundle\Factory\AutoResponderDataFactory
    netgen_information_collection.factory.captcha.class: Netgen\Bundle\InformationCollectionBundle\Form\Captcha\CaptchaService

services:
    netgen_information_collection.factory.email_data:
        class: '%netgen_information_collection.factory.email_data.class%'
        arguments:
            - "@ezpublish.config.resolver"
            - '@ezpublish.translation_helper'
            - '@ezpublish.field_helper'
            - '@ezpublish.api.service.content'
            - '@twig'

    netgen_information_collection.factory.auto_responder_data:
        class: '%netgen_information_collection.factory.auto_responder_data.class%'
        arguments:
            - "@ezpublish.config.resolver"
            - '@ezpublish.translation_helper'
            - '@ezpublish.field_helper'
            - '@ezpublish.api.service.content'
            - '@twig'

    netgen_information_collection.factory.field_data:
        class: '%netgen_information_collection.factory.field_data.class%'
        arguments:
            - '@netgen_information_collection.field_handler.registry'

    netgen_information_collection.factory.captcha:
        class: '%netgen_information_collection.factory.captcha.class%'
        arguments:
            - "@ezpublish.api.service.content_type"
            - "@ezpublish.config.resolver"
