services:
    netgen_information_collection.field_handler.checkbox:
        class: Netgen\Bundle\InformationCollectionBundle\FieldHandler\Custom\CheckboxFieldHandler
        tags:
            - { name: netgen_information_collection.field_handler.custom }

    netgen_information_collection.field_handler.integer:
        class: Netgen\Bundle\InformationCollectionBundle\FieldHandler\Custom\IntegerFieldHandler
        tags:
            - { name: netgen_information_collection.field_handler.custom }

    netgen_information_collection.field_handler.float:
        class: Netgen\Bundle\InformationCollectionBundle\FieldHandler\Custom\FloatFieldHandler
        tags:
            - { name: netgen_information_collection.field_handler.custom }

    netgen_information_collection.field_handler.date:
        class: Netgen\Bundle\InformationCollectionBundle\FieldHandler\Custom\DateFieldHandler
        tags:
            - { name: netgen_information_collection.field_handler.custom }

    netgen_information_collection.field_handler.time:
        class: Netgen\Bundle\InformationCollectionBundle\FieldHandler\Custom\TimeFieldHandler
        tags:
            - { name: netgen_information_collection.field_handler.custom }

    netgen_information_collection.field_handler.date_and_time:
        class: Netgen\Bundle\InformationCollectionBundle\FieldHandler\Custom\DateAndTimeFieldHandler
        tags:
            - { name: netgen_information_collection.field_handler.custom }
