imports:
    - { resource: controllers.yml }

services:
    netgen_information_collection.command.anonymize:
        arguments:
            - '@netgen_information_collection.anonymizer_facade.service'
        tags:
            - { name: console.command }

    netgen_information_collection.param_converter.collection:
        class: Netgen\Bundle\InformationCollectionBundle\ParamConverter\CollectionParamConverter
        arguments:
            - '@netgen_information_collection.api.service'
        tags:
            - { name: request.param_converter }

    netgen_information_collection.collector:
        class: Netgen\Bundle\InformationCollectionBundle\DataCollector\InformationCollectionCollector
        public: false
        tags:
            - { name: data_collector, template: '@NetgenInformationCollection/data_collector/template.html.twig', id: 'netgen_information_collection_collector' }
